### PR TITLE
Added a program called Subsequences.cpp which prints the Subseqences of a string

### PR DESCRIPTION
**Pull request by NuclearCactus**
The program takes a string from the user as input and uses recursion to print its subsequences. The code is written in C++.

### CODE REVIEW

**Comment by zeel-codder** [comment]
Thanks for contributing.
Just add programe file name in README.md file list part.

**Comment by NuclearCactus** [comment]
@zeel-codder I saw today that the Readme.md and contributing rules have changed. I am submitting another pull request to add the code in markdown as you specified

**Comment by NuclearCactus** [comment]
@zeel-codder For some reason I am not being able to merge my new PR where I contributed my original program as .md file. Can you please help me with this?

**Comment by zeel-codder** [comment]
What Error you getting

**Comment by NuclearCactus** [comment]
> What Error are you getting?

@zeel-codder I am not even getting the 'Compare and Pull Request Button' on the the repo after pushing the changes from my PC

**Comment by zeel-codder** [comment]
> > What Error are you getting?
> 
> @zeel-codder I am not even getting the 'Compare and Pull Request Button' on the the repo after pushing the changes from my PC

If you able to see changes on repo.

**Comment by zeel-codder** [comment]
Do one thing just close this pr and remove repo.then refork and make pr. :-)

**Comment by NuclearCactus** [comment]
> Do one thing just close this pr and remove repo.then refork and make pr. :-)

Alright I'm doing that then @zeel-codder

**Pull request closed without merging**
