### PR TITLE
solved reversingArray.md in c++

### PR DESCRIPTION
**Pull request by sujaykummari**

### CODE REVIEW

**Comment by zeel-codder** [comment]
Also if you don't have a website then just don't add it to the top.
Thank you

**Comment by sujaykummari** [comment]
Thank you

**Comment by zeel-codder** [comment]
https://raw.githubusercontent.com/zeel-codder/Recursion-Hub/main/Code/FibonacciNumber.md, see this
write in this format. :)

**Comment by sujaykummari** [comment]
Updated , Thanks

**Pull request merged**
