### PR TITLE
issue #95 fixed

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
Problem: Some documents was having `undefined` members
Solved: Changed TRY & CATCH statment position

App won't crash anymore

review Required: @zeel-codder

_ShGI_

### CODE REVIEW

**Comment by SGI-CAPP-AT2** [comment]
Result After change:
image

**Comment by SGI-CAPP-AT2** [comment]
@zeel-codder  

- [ ] add `hactoberfest-accepted` at time of pr merge
- [ ] add `hacktoberfest` topic to repo

**Comment by SGI-CAPP-AT2** [comment]
@zeel-codder check this

**Comment by zeel-codder** [comment]
gg man

**Pull request merged**
