### PR TITLE
Added check if a string is a rotated palindrome or not question

### PR DESCRIPTION
**Pull request by Himanshu664**
Check if a string is a rotated palindrome or not question added

### CODE REVIEW

**Comment by Himanshu664** [comment]
@zeel-codder please review.

**Comment by zeel-codder** [comment]
hi, please go to the readme file As there is a major change in the project.
https://github.com/zeel-codder/Recursion-Hub#readme

**Comment by Himanshu664** [comment]
I have to commit new changes in this PR to get merged

**Comment by zeel-codder** [comment]
hi, please go to the readme file As there is a major change in the project.
https://github.com/zeel-codder/Recursion-Hub#readme

**Comment by Himanshu664** [comment]
@zeel-codder please review

**Comment by zeel-codder** [comment]
ok

**Pull request merged**
