### PR TITLE
🛠️ UI & Search error fixed

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
problem was: can not read match() of undefined
solved: true
ERROR before fix:
image
Search after fix:
image

Review: @zeel-codder 

Thanks,
ShGI

### CODE REVIEW

**Comment by SGI-CAPP-AT2** [comment]
@zeel-codder 
#97 is done with this push to fork
Search ERR:
https://github.com/zeel-codder/Recursion-Hub/pull/98/commits/a9f20c2edfa761ace44b3b8a826bce5c869827c4
UI:
https://github.com/zeel-codder/Recursion-Hub/pull/98/commits/636b30016242310faefddb80aacb5ab36992b702

Review @zeel-codder ,
Thanks,
@SGI-CAPP-AT2

**Review by SGI-CAPP-AT2 — COMMENTED** [review]
Review By @SGI-CAPP-AT2

**Comment by SGI-CAPP-AT2** [comment]
Updated UI
image
Search fix
[RCHUB HF 22 Search.webm](https://user-images.githubusercontent.com/77089227/193594849-cb60d78b-4ebf-4563-9d82-100abcb46c30.webm)

**Comment by zeel-codder** [comment]
nice

**Pull request merged**
